Results of doctest builder run on 2015-06-13 20:15:12
=====================================================

Document: index
---------------
**********************************************************************
File "index.rst", line 20, in default
Failed example:
    s = requests.Session()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        s = requests.Session()
    NameError: name 'requests' is not defined
**********************************************************************
File "index.rst", line 21, in default
Failed example:
    login(s, "guest", "123")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        login(s, "guest", "123")
    NameError: name 'login' is not defined
**********************************************************************
File "index.rst", line 25, in default
Failed example:
    login(s, "guest", "777")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        login(s, "guest", "777")
    NameError: name 'login' is not defined
**********************************************************************
File "index.rst", line 22, in default
Failed example:
    s = requests.Session()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        s = requests.Session()
    NameError: name 'requests' is not defined
**********************************************************************
File "index.rst", line 23, in default
Failed example:
    content = query(s, "ag222", {"arg01": "103", "arg02": "2"})
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        content = query(s, "ag222", {"arg01": "103", "arg02": "2"})
    NameError: name 'query' is not defined
**********************************************************************
File "index.rst", line 24, in default
Failed example:
    "Please Logon" in content
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        "Please Logon" in content
    NameError: name 'content' is not defined
**********************************************************************
File "index.rst", line 27, in default
Failed example:
    login(s, "guest", "123")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        login(s, "guest", "123")
    NameError: name 'login' is not defined
**********************************************************************
File "index.rst", line 35, in default
Failed example:
    content = query(s, "ag202", args)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[1]>", line 1, in <module>
        content = query(s, "ag202", args)
    NameError: name 'query' is not defined
**********************************************************************
File "index.rst", line 36, in default
Failed example:
    "內部控制暨稽核制度" in content
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[2]>", line 1, in <module>
        "內部控制暨稽核制度" in content
    NameError: name 'content' is not defined
**********************************************************************
File "index.rst", line 10, in default
Failed example:
    status()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        status()
    NameError: name 'status' is not defined
**********************************************************************
1 items had failures:
  10 of  11 in default
11 tests in 1 items.
1 passed and 10 failed.
***Test Failed*** 10 failures.

Doctest summary
===============
   11 tests
   10 failures in tests
    0 failures in setup code
    0 failures in cleanup code
